### ISSUE TITLE
Script malfuction when rendering a video with 60 FPS

### ISSUE THREAD

**Issue by FinalLeet** [kumfc/sfm-tools#2]
Hello, first time using this site, sorry for the delays..

After some time the script stops working, break the flexes and sometimes jiggle bones. 

Thought the time it occurs varys each time based on amount of models.

https://gfycat.com/quarterlycoordinatedbuffalo , 2 scouts both rendered with default rendering(DOF,SUB, no motion blur) settings.

https://gfycat.com/largemedicaldassie ,(sorry for bad edit) another test based on a scene from one of my projects, somewhere between 54 and 60 FPS it starts to break. With higher rendering FPS (above 24~30), you'd notice some of the flexes loses some of it's power [happened on the frame where she closes her eyes like >.<]. 

https://gfycat.com/harshzanyfrogmouth Another test with multiple models ported from MMD, the script broke much quicker (models remained with low jitter in the end). <- tried rendering the same scene with triple the duration in 30FPS, but it worked fine.

**Comment by kumfc** [comment]
Wouldn't it jiggle bones at 60fps even without the script? The code we patch has nothing to do with jiggle bones so it's kind of weird.

**Comment by kumfc** [comment]
Doesn't seem to reproduce for me. Do you use frame override or set 60fps on session creation?
Do you have the script always loaded during the animation process? Have been any flexes animated in a way they go above the limit?

**Comment by FinalLeet** [comment]
1.  The jiggle bones works fine when rendered in 60fps without the script. Not sure how the it scaled/pulled the ears atleast, i tried once with jiggles off, and it didn't bug out.
2. I keep most of my sessions at 24, so i had to use the override. Regrading the loadings of the script, i do it once when flex animating.. might be due to sometimes I load it twice or more per session and saving.

**Comment by kumfc** [comment]
Got some evidence that this problem is presented in vanilla SFM (FPS override is bugging out when interpolating frames). This script just makes it more noticeable due to the higher flex values.
