### ISSUE TITLE
TF2 Cosmetics on Scaled Mercenaries

### ISSUE THREAD

**Issue by GmodViolet** [kumfc/sfm-tools#3]
Hello!
I wanted to report an issue a friend of mine encountered.

Apparently, scaled TF2 Mercenaries wearing cosmetics doesn't scale the cosmetics.

They haven't be able to find a solution to that problem and thus, I wanted to know if it was solvable or not.

If not, could this be fixed in the future, please? Thank you.

Also, I'm sorry. This is my first time using this site.

**Comment by kumfc** [comment]
We'll check if that's possible

**Comment by kumfc** [comment]
Should be fixed now
