### ISSUE TITLE
Problems with the script in New Choke folder #bug #directional-scale-controls

### ISSUE THREAD

**Issue by DavidromeSFM** [kumfc/sfm-tools#7]
It seems its a problem that it doesnt happen to everyone, but at the same time its a problem i dont a solution, every time im trying to apply that script, it gives me error and it shows me that the problem are in two lines and then in an attribute, so it would be helpful if someone help me with this problem 

![2](https://user-images.githubusercontent.com/129671754/229357858-9e3849f6-6433-4dd9-8dd1-096696c880b8.JPG)

**Comment by kumfc** [comment]
Can you make a screencast of what you are trying to do?

**Comment by kumfc** [comment]
No response
